version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app: 
    container_name: teravoz-client
    restart: always
    build: .
    ports:
      - '8000:8000'
      - '4200:4200'
    links:
      - mongo
